name: Run Tests

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Run Jest tests
        run: yarn test

      - name: Create coverage badge
        uses: tj-actions/badge@v1.8
        with:
          label: coverage
          value: ${{ steps.test.outputs.coverage }}
          status: ${{ steps.test.outputs.status }}
